services:
  - type: web
    name: vr-hotspots-educational
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: vr-hotspots-storage
      mountPath: /opt/render/project
      sizeGB: 1
